/* eslint-disable @typescript-eslint/triple-slash-reference */
/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />


// Cache name and timestamp to distinguish different caches
const CACHE_NAME = 'v1'; 
const TIMESTAMP = '04092023'; 

// `build` is an array of all the files generated by the bundler,
// `files` is an array of everything in the `static` directory
const worker = self as unknown as ServiceWorkerGlobalScope;
import { build, files, version } from '$service-worker';
const to_cache = build.concat(files);
const staticAssets = new Set(to_cache);

// Install event - cache static assets
worker.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(to_cache))
      .then(() => {
        worker.skipWaiting();
      })
  );
});

// Activate event - clear old caches
worker.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then(async (keys) => {
      for (const key of keys) {
        if (key !== CACHE_NAME) await caches.delete(key);
      }
      worker.clients.claim();
    })
  );
});

/**
 * Fetch the asset from the network and store it in the cache.
 * Fall back to the cache if the user is offline.
 */
async function fetchAndCache(request: Request) {
  const cache = await caches.open(`offline${TIMESTAMP}`);

  try {
    const response = await fetch(request);
    cache.put(request, response.clone());
    return response;
  } catch (err) {
    const response = await cache.match(request);
    if (response) return response;

    throw err;
  }
}

// Fetch event - serve static assets from cache
worker.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET' || event.request.headers.has('range')) return;

  const url = new URL(event.request.url);
  const isHttp = url.protocol.startsWith('http');
  const isDevServerRequest =
    url.hostname === self.location.hostname && url.port !== self.location.port;
  const isStaticAsset = url.host === self.location.host && staticAssets.has(url.pathname);
  const skipBecauseUncached = event.request.cache === 'only-if-cached' && !isStaticAsset;

  if (isHttp && !isDevServerRequest && !skipBecauseUncached) {
    event.respondWith(
      (async () => {
        const cachedAsset = isStaticAsset && (await caches.match(event.request));

        return cachedAsset || fetchAndCache(event.request);
      })()
    );
  }
});

// Push event - handle push notifications
worker.addEventListener('push', function (event: PushEvent) {
  const iconUrl = '/logo.png';
  const pushData = event.data?.json(); // Parse the event data as JSON

  // Extract the head, body, and click data from the push data
  const head = pushData?.head || 'FoodStock'; // Use a default title if not provided
  const body = pushData?.body || "This is default content. Your notification didn't have one 🙄🙄";
  const clickData = pushData?.click_data || {};

  event.waitUntil(
    worker.registration.showNotification(head, {
      body: body,
      icon: iconUrl,
      data: clickData,
    })
  );
});

// Notification click event - handle notification click actions
worker.addEventListener('notificationclick', function (event: NotificationEvent) {
  event.notification.close();

  // Retrieve the click data from the notification
  const clickData = event.notification.data;

  if (clickData && clickData.url) {
    event.waitUntil(
      (self as any).clients
        .matchAll({
          type: 'window',
          includeUncontrolled: true, // Include uncontrolled clients (e.g., a background tab)
        })
        .then(function (clientList) {
          // Check if there's an open window for the same app
          for (const client of clientList) {
            if (client.url === clickData.url && 'focus' in client) {
              return client.focus();
            }
          }
          // If no existing window, open a new one
          if ((self as any).clients.openWindow) {
            return (self as any).clients.openWindow(clickData.url);
          }
        })
    );
  }
});


